# Site settings
title: Arvind Kamal
description: Arvind Kamal
baseurl: "" # "/will-jekyll-template" - the subpath of your site, e.g. /blog
url: "https://arvindkamal.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Arvind Kamal
user_description: Engineer. Photographer. Shooter.
user_title: Engineer. Photographer. Shooter.
email: reach.arvind.kamal@gmail.com
twitter_username: thearvindkamal
dpost_username: arvindkamal
linkedin_username: arkamal
#github_username:  lorem_ipsum
#gplus_username:  lorem_ipsum
#disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Tags
    url: /tags
  - title: About Me
    url: /about
  #- title: Series
  #  url: /series

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
future: true
